Week11/Profiles copy/config/routes.rb
Rails.application.routes.draw do

  root "profiles#index"
  get '/profiles/adminindex', to: 'profiles#adminindex'

  resources :customs
  resources :certifications
  resources :employments
  resources :educations
  resources :projects
  resources :sections do
    collection do
      patch :sort
    end
  end
  resources :profiles
  get '/login', to: 'session#login'
  get '/logout', to: 'session#logout'
  post '/login', to: 'session#create'
  get '/token/:token', to: 'tokenurl#show'

  get '/token' => 'profiles#token', :as => 'token'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Week11/Profiles copy/app/models/custom.rb
class Custom < ApplicationRecord

    # validating the form inputs; PM-28 PM-31
    validates :body, presence: true, length: { maximum: 600 }
    validates :title, presence: true, length: { minimum: 5, maximum: 40 }

end

Week11/Profiles copy/app/controllers/customs_controller.rb
class CustomsController < ApplicationController
  before_action :set_custom, only: [:show, :edit, :update, :destroy]
  before_action :check_login

  # GET /customs
  # GET /customs.json
  def index
    @customs = Custom.where(user_id: current_user.id)
  end

  # GET /customs/1
  # GET /customs/1.json
  def show
  end

  # GET /customs/new
  def new
    @custom = Custom.new
  end

  # GET /customs/1/edit
  def edit
  end

  # POST /customs
  # POST /customs.json
  def create
    @custom = Custom.new(custom_params)
    @custom.user_id = current_user.id
    respond_to do |format|
      if @custom.save
        format.html { redirect_to customs_url, notice: '*Custom was successfully created.' }
        format.json { render :show, status: :created, location: @custom }
      else
        format.html { render :new }
        format.json { render json: @custom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customs/1
  # PATCH/PUT /customs/1.json
  def update
    @custom.user_id = current_user.id
    respond_to do |format|
      if @custom.update(custom_params)
        format.html { redirect_to customs_url, notice: '*Custom was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom }
      else
        format.html { render :edit }
        format.json { render json: @custom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customs/1
  # DELETE /customs/1.json
  def destroy
    @custom.destroy
    respond_to do |format|
      format.html { redirect_to customs_url, notice: '*Custom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom
      @custom = Custom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_params
      params.require(:custom).permit(:title, :heading, :body)
    end
end

Week11/Profiles copy/app/helpers/customs_helper.rb
module CustomsHelper
end

Week11/Profiles copy/app/views/customs/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_with(model: custom, local: true) do |form| %>
      <% if custom.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(custom.errors.count, "error") %> prohibited this custom from being saved:</h2>

          <ul>
          <% custom.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group" >
        <%= form.label :title_of_section %>
        <%= form.text_field :title, class: "form-control", id: "title", maxLength:40 %>
        <p>Remaining Characters: 40 </p>
      </div>

      <div class="form-group" >
        <%= form.label :heading %>
        <%= form.text_field :heading, class: "form-control", id: "heading", maxLength: 40 %>
        <p>Maximum characters allowed: 40</p>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", id: "body", rows: 20, maxLength:600 %>
        <p>Remaining Characters: 600</p>
      </div>

      <div class="form-group">
        <%= form.submit "Save" , class: "btn btn-primary", id: "save-button" %>
      </div>
    <% end %>
  </div>
</div>

Week11/Profiles copy/app/views/customs/edit.html.erb
<h1 class="header">Editing Custom</h1>

<%= render 'form', custom: @custom %>

<%= link_to 'Show', @custom, id: 'show-button'%> |
<%= link_to 'Back', customs_path, id: 'back-button'%>

Week11/Profiles copy/app/views/customs/index.html.erb
<h1 class="header">Custom Sections</h1>


<p>This section is for additional sections if you feel there's more information that you need to include as part of your profile.</p>
<p>You can add a new section by 'New Custom Section'</p>
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%id = 0 %>
    <% @customs.each do |custom| %>
      <tr>
        <td><%= link_to custom.title, edit_custom_path(custom), id: "title-#{id}" %></td>
        <td><%= link_to 'Destroy', custom, method: :delete, data: { title: 'Delete Section', confirm: 'Are you sure?', id: "destroy-#{id}" } %></td>
      </tr>
    <%id = id + 1%>
    <% end %>
    <tr>
      <td colspan="5" class="text-center"><%= link_to 'New Custom Section', new_custom_path, class: "btn btn-primary", id: "new-button" %></td>
    </tr>
  </tbody>
</table>

Week11/Profiles copy/app/views/customs/new.html.erb
<h1 class="header">New Custom</h1>
<p>You can add your custom sections using this form.</p>
<p>Please enter a title for the custom section, a heading, and the body of your section.</p>
<p><em>All fields are required.</em></p>

<%= render 'form', custom: @custom %>

<%= link_to 'Back', customs_path, id: 'back-button'%>

Week11/Profiles copy/app/views/customs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @custom.title %>
</p>

<p>
  <strong>Heading:</strong>
  <%= @custom.heading %>
</p>

<p>
  <strong>Body:</strong>
  <%= @custom.body %>
</p>


<%= link_to 'Edit', edit_custom_path(@custom), id: 'edit-button' %> |
<%= link_to 'Back', customs_path, id:'back-button'%>