Week6/wednesday/blog_site_with_comments/config/routes.rb
Rails.application.routes.draw do

  get 'about', to: 'misc#about', as: 'about'
  get 'contact', to: 'misc#contact', as: 'contact'
  get 'faq', to: 'misc#FAQ', as: 'faq'
  get 'terms', to: 'misc#terms', as: 'terms'
  get '', to: 'misc#index', as: 'index'

  # get 'posts', to: 'posts#index', as: 'home'
  #
  # get 'posts/new', to: 'posts#new', as: 'new'
  #
  # get 'posts/:id', to: 'posts#show', as: 'post'
  #
  # get 'posts/:id/edit', to: 'posts#edit', as: 'edit'

  resources :posts do
    resources :comments
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'


end

Week6/wednesday/blog_site_with_comments/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Week6/wednesday/blog_site_with_comments/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

Week6/wednesday/blog_site_with_comments/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  validates :title, :body, presence: true
  validates :title, length: {message: "must contain 10 characters or more", minimum: 10}
end

Week6/wednesday/blog_site_with_comments/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Week6/wednesday/blog_site_with_comments/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to @post
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  def comment_params
    params.require(:comment).permit(:name,:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end


end

Week6/wednesday/blog_site_with_comments/app/controllers/misc_controller.rb
class MiscController < ApplicationController
  def about
  end

  def contact
  end

  def FAQ
  end

  def terms
  end

  def index
  end
end

Week6/wednesday/blog_site_with_comments/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html{redirect_to @post, notice: "' #{@post.title}' was created"}
      else
        format.html{render :new}
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    respond_to do |format|
      if @post.update(post_params)
        format.html{redirect_to @post, notice: "' #{@post.title}' was successfully updated"}
      else
        format.html{render :edit}
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:title,:body,:author)
  end

end

Week6/wednesday/blog_site_with_comments/app/helpers/application_helper.rb
module ApplicationHelper
end

Week6/wednesday/blog_site_with_comments/app/helpers/misc_helper.rb
module MiscHelper
end

Week6/wednesday/blog_site_with_comments/app/helpers/posts_helper.rb
module PostsHelper
end

Week6/wednesday/blog_site_with_comments/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render partial: 'partials/comment_form', locals: {comment: @comment}%>

Week6/wednesday/blog_site_with_comments/app/views/partials/_comment.html.erb
<div class="">

<b><%= comment.name %>:</b>
<p><%= comment.content %></p>

<%= link_to "Edit", edit_post_comment_path(@post, comment) %>
<%= link_to 'Delete', [@post, comment], method: :delete %>
<br><br>
</div>

Week6/wednesday/blog_site_with_comments/app/views/partials/_comment_form.html.erb
<%= form_for([@post, comment]) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

Week6/wednesday/blog_site_with_comments/app/views/partials/_footer.html.erb
<hr>
<%= link_to "About", about_path %> |
<%= link_to "FAQ", faq_path %> |
<%= link_to "Contact", contact_path %> |
<%= link_to "Terms", terms_path %> |
<%= link_to "Index", index_path %>

Week6/wednesday/blog_site_with_comments/app/views/partials/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
  <h3><i><%= pluralize(post.errors.count, 'error') %> to fix</i></h3>
  <ul>
    <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

Week6/wednesday/blog_site_with_comments/app/views/partials/_navbar.html.erb
<%= link_to 'Home', posts_path %> |
<%= link_to "New Post", new_post_path %>